### PR TITLE
fixes #2

### LINKED ISSUE #2: Update assets to 3.9.2
Hi here. Would be nice to update to latest stable [3.9.2](https://github.com/swagger-api/swagger-ui/tree/v3.9.2) assets which support OpenAPI 3.0 specification.

Obviously I can put new assets into package, but I think it would be great to have them here in one place.

### PR DESCRIPTION
**Pull request by dselivanov**
Assets from official 3.9.2 release - https://github.com/swagger-api/swagger-ui/releases/tag/v3.9.2

### CODE REVIEW

**Comment by dselivanov** [comment]
@javierluraschi are you interested to update assets? Please let me know if not, I will submit another package to CRAN.

**Comment by jjallaire** [comment]
@javierluraschi Is in the middle of preparing a talk for a conference (plus working on related software) so might not be able to get to this issue for a few days.

**Comment by javierluraschi** [comment]
Thank you @dselivanov, sorry for the delayed response.

**Comment by dselivanov** [comment]
OFFTOPIC:
@javierluraschi also I was thinking about possible security breaks in such type of PR. It contains a lot of minified javascript. So it is not possible to check code manually (could be some backdoor inside). I would suggest to at least calculate md5 or similar hash and compare it the ground of truth (code from original repo).

**Comment by javierluraschi** [comment]
@dselivanov makes sense, I think we should add a test. Here is the issue: https://github.com/rstudio/swagger/issues/4, feel free to take a stab at that if you have a chance. I should ask, when would you ideally like to see this change in CRAN?

**Comment by dselivanov** [comment]
Thanks. I'm developing package which has swagger in suggests (not publicly available yet). Would be great to update `swagger` pkg on CRAN within month or so (if it is comfortable for you).

**Comment by javierluraschi** [comment]
@dselivanov yes, I can update swagger in February in CRAN.

**Comment by dselivanov** [comment]
@javierluraschi gentle reminder about CRAN release

**Comment by javierluraschi** [comment]
Submitted to CRAN, give it a day or two, thanks for the reminder @dselivanov!

**Pull request merged**
